const mongoose = require("mongoose");
const axios = require("axios");
require("dotenv").config({ path: "d:/jan2026/magnifAi/backend/.env" });

const { CEO } = require("../src/models/CEO");

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  const ceo = await CEO.findOne({ email: "singhlakshmiraj@gmail.com" });

  const apiBaseUrl = process.env.WHATS_AI_API_BASE_URL;
  const partnerKey = process.env.WHATS_AI_PARTNER_KEY;
  const clientToken = process.env.WHATS_AI_ACCESS_TOKEN;
  const ref = process.env.WHATS_AI_REFERENCE_KEY;
  const apiKey = process.env.WHATS_AI_API_KEY || "whatsai-core-master-secret-key-2026";

  const handshakeRes = await axios.post(
    `${apiBaseUrl.replace(/\/$/, "")}/api/auth/api-sharing-login`,
    {
      apiSharingKey: partnerKey,
      accessToken: clientToken,
      referenceKey: ref
    },
    {
      headers: {
        "x-api-key": apiKey,
        "Content-Type": "application/json"
      }
    }
  );
  const token = handshakeRes.data?.token || handshakeRes.data?.data?.token || handshakeRes.data?.data?.accessToken || handshakeRes.data?.accessToken;

  const headers = {
    "Authorization": `Bearer ${token}`,
    "x-api-key": partnerKey,
    "x-client-id": ceo.whatsAppClientId,
    "Content-Type": "application/json"
  };

  // Recipient: Hirdesh Nawani (919953100111)
  const phone = "919953100111";

  // Test Case 1: Send with 2 parameters (as generated by campaign variable mappings)
  console.log("\n--- Test Case 1: Sending with 2 variables ---");
  try {
    const res = await axios.post(`${apiBaseUrl.replace(/\/$/, "")}/api/inbox/send-template`, {
      phone,
      templateName: "ai_assistant",
      language: "en",
      variables: [
        { key: "1", value: "HIRDESH NAWANI" },
        { key: "2", value: "Lakshami Raj Singh" }
      ]
    }, { headers });
    console.log("Success:", res.data);
  } catch (err) {
    console.error("Failed:", err.response?.data || err.message);
  }

  // Test Case 2: Send with exactly 1 parameter
  console.log("\n--- Test Case 2: Sending with 1 variable ---");
  try {
    const res = await axios.post(`${apiBaseUrl.replace(/\/$/, "")}/api/inbox/send-template`, {
      phone,
      templateName: "ai_assistant",
      language: "en",
      variables: [
        { key: "1", value: "Lakshami Raj Singh" }
      ]
    }, { headers });
    console.log("Success:", res.data);
  } catch (err) {
    console.error("Failed:", err.response?.data || err.message);
  }

  process.exit(0);
}

run().catch(e => {
  console.error(e);
  process.exit(1);
});
